### ISSUE TITLE
Not all uploaded files are encrypted

### ISSUE THREAD

**Issue by happybeing** [maidsafe/autonomi#1103]
I think files under a certain size are not yet being encrypted so raising this issue to highlight this. I tested this by just doing a grep for a common word in the record_store of my 13 nodes and multiple records were found to contain plaintext. 

Obviously this is not satisfactory for MVP/beta, but I also wonder if it could affect distribution of data among nodes, being less random than encrypted chunks.

**Comment by joshuef** [comment]
Could affect distribution aye. There's no real way for nodes to reject unencrypted data though 🤔 

I wonder if we should probably just pad such small data if we're putting it up and reject anything less than a chunk? Then at least users wouldn't accidentally store unencrypted data eg.

**Comment by happybeing** [comment]
Padding might be a safe 😉 default, so long as it doesn't overly restrict use because an application might handle that differently. 

So may make sense as a feature in safe client that is optional but on by default.

**Comment by joshuef** [comment]
Update as per the forum: https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet/39034/272?u=joshuef

Miminal plan is thus:


   
- Nodes encrypt data themselves
- sn_client errors if data cannot be encrypted (ie no surprise public data!)
- sn_cli wraps sn_client and self encryption layers to ensure all data is encrypted in some fashion via encrypted registers (ie, normal users get all data encrypted via CLI).

**Comment by joshuef** [comment]
ll close this as we've got a more specific set of follow on issues here. Thanks @happybeing !

**Comment by JasonPaulGithub** [comment]
This is linked to https://github.com/maidsafe/safe_network/issues/1487
Which is what I'm working on. Hope that helps 👍
