### ISSUE TITLE
Latency and Scalability

### ISSUE THREAD

**Issue by lonnietc** [maidsafe/autonomi#1119]
Greetings All,

I have just come across the Safe Network project and am greatly interested in its possible use.

With that in mind, I was wondering about scalability and latency as compared to perhaps other solutions like IPFS and NKN Blockchain?

Any thoughts or comments would be greatly appreciated.

Thanks and have a great day.

**Comment by happybeing** [comment]
I suggest you post this question on the forum: https://safenetforum.org

**Comment by joshuef** [comment]
Going to close this as indeed such discussion is better on the forum. See you over there hopefully @lonnietc ! 🙇
