### ISSUE TITLE
Add rust documentation and doctests to `sn_client`

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#1135]
We need to go over the `sn_client` APIs to ensure they are correctly documented and add doctests where appropriate to ensure the code and docs match and are building correctly.

(This could be batches of small PRs, updating docs for one API at a time)

**Comment by JasonPaulGithub** [comment]
Thanks @joshuef. I'm going to go apply these resources to my approach:

https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html
https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html
https://rust-lang.github.io/api-guidelines/documentation.html
https://crates.io/crates/sn_client
https://docs.rs/sn_client/latest/sn_client/
