### ISSUE TITLE
Spaces are not handled well for file upload/download

### ISSUE THREAD

**Issue by willief** [maidsafe/autonomi#1145]
It was noticed in the forum 
https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet/39034/156?u=southside https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet/39034/169?u=southside

that uploads with spaces in the file name tend to fail whilst the same file uploaded with a filename not containing spaces work as expected.
Credit to @nos for noticing this

**Comment by JasonPaulGithub** [comment]
I have failed to recreate this bug. A file with spaces in the name was uploaded and downloaded without issue.
Is this bug still an issue? If so perhaps I can take a closer look.

**Comment by JasonPaulGithub** [comment]
@willief @joshuef
I have failed to recreate this bug. A file with spaces in the name can be uploaded and downloaded.
Is this bug still an issue? If so perhaps I can take a closer look.

**Comment by joshuef** [comment]
Closing this as we cannot reproduce. Please reopen @willief if you're still able to do so.
