### ISSUE TITLE
Is there a reference implementation of P.O.R?

### ISSUE THREAD

**Issue by jakubDoka** [maidsafe/autonomi#1175]
Hello, I'd like to better understand how the Proof of Resource works, I looked around in whitepapers and found mentions of it, but I cannot really verify if the P.O.R is secure for replicating data, for example, how does one know that a node has the data on its drive and is not fetching id from elsewhere?

**Comment by joshuef** [comment]
Hey @jakubDoka , we'll actually likely be dropping PoR as a term in the network. 

>how does one know that a node has the data on its drive and is not fetching id from elsewhere?

What we'll likely do is actually just detect any nodes over-requesting data they should be holding and thereafter excommunicate them.
