### ISSUE TITLE
Archive & DAG nodes

### ISSUE THREAD

**Issue by oetyng** [maidsafe/autonomi#139]
Nodes should use what space they can and when they cannot store any more they will be caught by failure tests.

However, we can allow nodes to dump excess data to Archive nodes and suffer no penalty.

Archive nodes and DAG audit nodes are based on the premise that folk with large disks will want to help.
As yet no incentives, but doing this secures DBCs much more as these are randomly served by nodes and can provide backup to the query of "have you seen this parent and can you see any double spend attempt?".

Secure chunks and registers with random large disks spread around.

This is a really positive step we can take now as the Safe network has almost no authority. All data is validatable and all the Safe network needs to do is make it available. So network Authority is really **Store** and **Give**, no _creation_.

Because of that we can have backup networks, backup nodes and so on making the network more resilient in a way that's unpredictable and therefore hard to attack.

**Comment by joshuef** [comment]
Closing this as fairly vague. We'll be diving more into potential dag-likes soon though.
