### ISSUE TITLE
(node manager) Display Multiaddr in network status

### ISSUE THREAD

**Issue by loziniak** [maidsafe/autonomi#1457]
It would be very useful to have nodes **Multiaddr** in `safenode-manager -v status` output. It would make connecting by client with `--peers` or `SAFE_PEERS` easier.

**Comment by jacderida** [comment]
Thanks for the feedback.

The multiaddr is printed in `status --details`.

**Comment by loziniak** [comment]
Haha I just noticed that! Thanks!
