### ISSUE TITLE
Provide a `--version` Argument for `safenode_rpc_client`

### ISSUE THREAD

**Issue by jacderida** [maidsafe/autonomi#1513]
Minor issue, but a user pointed out that this doesn't work for `safenode_rpc_client`.

**Comment by mickvandijke** [comment]
Should this return the `binary version` specified in the `cargo run --bin safenode_rpc_client <ADDRESS> info` command?

**Comment by mickvandijke** [comment]
Hi @jacderida ,

Should this return the `binary version` specified in the `cargo run --bin safenode_rpc_client <ADDRESS> info` command?
