### ISSUE TITLE
API for uploading a directory tree - some questions

### ISSUE THREAD

**Issue by happybeing** [maidsafe/autonomi#1576]
I'm looking for an API for uploading a directory tree. The `sn_cli` `ChunkManager` seems to do everything I need, but once it completes I don't see a way for the app match the *path* of an uploaded file to the xor address of its datamap. The `ChunkManager` keeps track of the filenames and their xor addresses, but not the paths to the files.

I assume there isn't an alternative API that allows uploading of a directory tree, and tracks the paths.

So would you consider a PR to modify the `ChunkManager` to track the path of the file (and/or the name, since the name can be obtained from the path if that is retained)? In the short term it may be easier for me to build a separate crate with the API I need (and modified `ChunkManager`). So an alternative would be for me to do that and at some point the `sn_cli` could be modified to use that.

So I'm curious if these APIs might be better separated from the `sn_cli` crate which doesn't seem to be a good location for things used by other apps.

Any thoughts?

**Comment by happybeing** [comment]
I have now integrated the `FilesUploader` into my app so it would be ideal if that were able to provide a list of full paths and xor addresses for all the files in the tree, after successfully completing the upload. I'm not sure what the best way to do that will be.

`ChunkManager::completed_files` holds the name and xor address of the files. So if that could be modified to hold the full path and xor address, and then a way for this to be exposed by the `FilesUploader` that would mean a user of the `FilesUploader` can obtain the list of uploaded files (full paths) and their xor addresses after calling `FilesUploader::start_upload()`.

At the moment `FilesUploader::start_upload()` returns a summary of the chunks, so perhaps that could be changed as I'm not sure if it is used or useful.

EDIT: I've been looking into how to do this and it seems very difficult to get information from the `ChunkManager` (such as `ChunkManager::completed_files` to the user of a `FileUploader`. The `UploadSummary` might be used instead, but it doesn't know about files and doesn't have access to the `ChunkManager` so I don't see a simple way to expose the list of paths (or even filenames) that have completed or not completed, to a user of these APIs.

If that's true it is a problem for any app, so perhaps I am not understanding how to use these APIs from an app.

Can someone please explain how an app should upload a tree of files using the APIs, and how it can determine which files (with full paths) have uploaded? I believe I can work around this but think it is a useful thing to understand.

**Comment by RolandSherwin** [comment]
Hey @happybeing ! Thanks for digging in there, yeah, the `UploadSummary` is a direct export from the `Uploader` that deals with the low level chunks/registers. So maybe a high-level `FileUploadSummary` would be useful there, and it is possible to retrieve the info from the chunk manager with some minor refactoring. 

c.c @JasonPaulGithub Since you're working in that area, do you think you can make those changes?

**Comment by happybeing** [comment]
It would be great if this can be done.

I began working on a fork to do this but found it hard to see how to get the info out of the `ChunkManager` to the app API.

I thought I could work around this but have since realised I can't so will move to working on other aspects of my app and mock this feature while waiting hopefully!

I also posted on the dev forum about this and Josh pinged @bochaco there, so tagging here to avoid duplication.

Thanks for looking at this.

**Comment by RolandSherwin** [comment]
Hey @happybeing , I have raised a PR to fix this issue as you're currently blocked there. https://github.com/maidsafe/safe_network/pull/1586
I think this should be all that you need:
```/// The result of a successful files upload.
pub struct FilesUploadSummary {
    /// The cost and count summary of the upload.
    pub upload_summary: UploadSummary,
    /// The list of completed files (FilePath, FileName, HeadChunkAddress)
    pub completed_files: Vec<(PathBuf, OsString, ChunkAddress)>,
    /// The list of incomplete files (FilePath, FileName, HeadChunkAddress)
    pub incomplete_files: Vec<(PathBuf, OsString, ChunkAddress)>,
}
```

**Comment by happybeing** [comment]
That's b**** marvelous. You are a hero and thanks @bochaco for the speedy review.

I see from the changes I was right to leave this alone. Thank you, and the notifier is an extra nice touch.

I'm be using this this afternoon! 😄

**Comment by RolandSherwin** [comment]
😄 Glad that fixes your issue. I'll close this one!
