### ISSUE TITLE
Safenode Manager: services will not start on Windows 11

### ISSUE THREAD

**Issue by rreive** [maidsafe/autonomi#1589]
When Activating the MS Win11 Service  Window via PowerShell with Admin rights mode 

The Service Window opens
        Shows Services Local
                         Left hand panel  shows in description panel:
                                safenode<n>
                                  **Start** the service 

                                      Right hand panel shows
                                          Name               Description              Status          Startup Type    Logon As
                                      safenode1               <nothing>          <nothing>    Automatic       Local System
                                     
                                                                       

Where the view presents the admin with information which indicates
the safenode 1 is
                   NOT running   as there  is a blank , no information in status

As such any PowerShell Admin  logging into Win11 MS Service Manager will **incorrectly**

   attempt to **Start** the  service     (safenode <n>)  showing a blank in the status column 

 by  clicking a  local  mouse focus on the highlighted  "Start"  the service in the left hand panel

As the Powershell Administrator 

       which has the Win11 MS Service Manager application produce  

             first a 
 
                           Startup progress bar 

            then return 

                         an error msg window  saying 

                              "Windows could not start the safenode<n>  service on the Local Computer 

                                Error 1503  The service did not respond to the control request in a timely fashion

Screen snapshots of the process described above are attached

Suggested Remedies:

1. Add a more through description to the left hand panel  of what the servicenode is:
                ie- "Autonomi servicenode disk sharing service"   

2.  Given the servicenode  was started from PowerShell
             
             The  MS Win11 Service Manager should be signalled to set the status to 'running'

3.  Change the description title in the left hand panel, when a safenode start has been made from the PowerShell in Admin mode  to reflect both:
 
       a:       the "Automatic"   setup of the service to say

                      **"Restart"**  the  "Autonomi safenode service" 

       and

4.   Change the Status  Column from a blank to **"running"**
                           

To accurately reflect the state of the safenode in the MS Win11 after the safenode has been launched at the cli in the PowerShell with Adminstrator rights.

r2
![WIN Key_R Services Win11 Window  Start the Service msg error n_cli 0_90_4-alpha _5 Screenshot 2024-04-09 082837](https://github.com/maidsafe/safeup/assets/9811478/4667643e-99e4-492c-ab5a-78e84ceefdef)
![WIN Key_R Services Win11 Window Actions Sub Window  n_cli 0_90_4-alpha _5 Screenshot 2024-04-09 082837](https://github.com/maidsafe/safeup/assets/9811478/7383ccc7-8f4e-434e-af60-f9e877134c00)
![WIN Key_R Services Win11 Window Actions Sub Window Depend_tab  n_cli 0_90_4-alpha _5 Screenshot 2024-04-09 082837](https://github.com/maidsafe/safeup/assets/9811478/59b85696-9e63-40ec-b5c4-b1b9cddf3e45)
![WIN Key_R Services Win11 Window n_cli 0_90_4-alpha _5 Screenshot 2024-04-09 082837](https://github.com/maidsafe/safeup/assets/9811478/460c147d-6d5c-4c36-a4f2-04aea5a437ca)

**Comment by jacderida** [comment]
Hi @rreive 

Thanks for the feedback.

Just to let you know, this is related to the node manager, not to `safeup`.

I suspect the services will not start because you do not have `winsw` available. To use `safenode-manager` on Windows, you need to download [WinSW](https://github.com/winsw/winsw/releases/tag/v3.0.0-alpha.11), then rename the binary to `winsw.exe` and put it in a location that is available on the `Path` variable.

I have already raised issue maidsafe/safeup#26 to deal with supplying `WinSW` via `safeup`.

Please try to use the node manager after making `WinSW` available. For the services you have already added, you will need to remove them first, using `safenode-manager remove --service-name safenode1` and so on.

You should use `safenode-manager` to start the services rather than doing it manually in the Windows service manager.

I'll keep the issue open until you confirm you can get the services to start.

**Comment by rreive** [comment]
ok downloaded to safe folder in path variable, ran it,  works.. thanks  
safenode16         12D3KooWRdiEviafn15GwA9zxjhhopkCJYPZZigF1PgP9jzuj4JH RUNNING               0
safenode17         12D3KooWMViumA5isLQjvAmKFuoTG9gW2jKCMgT7oi2d7axvNuRJ RUNNING               0
safenode18         12D3KooWM8yHFEPwXcBE6PfFfUaW4NhNMX6aB1V125GvqAazXvBd RUNNING               0
safenode19         12D3KooWCnuh7SuB5z2Hh68q6oQ4QJunYxajBsk1ZJK31Dwxj7Kh RUNNING               0
safenode20         12D3KooWDnTBbrk9H5rXrWSUetNrMJrT9KzGb9RMnbQ1NjtfKbCn RUNNING               0

**Comment by jacderida** [comment]
OK great. Glad you got it working! I will close the issue now.
