### ISSUE TITLE
Debug AutoNat / Dctur performance via monitoring.

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#1732]

**Comment by b-zee** [comment]
One issue is that we're seeing lots of `MultiaddrNotSupported`. There's some information on why that might be happening here: https://github.com/libp2p/rust-libp2p/issues/2609#issuecomment-1141307790
However, it doesn't seem problematic per se. These addresses are dialed as an attempt to reach a peer through multiple transports at the same time and only this address fails. The connection will still be established if we have other valid addresses and that almost always seems the case.

On a large testnet we're currently running with NATed nodes: Counting the amount of DCUtR successes versus failures gives a success rate of 2.6%:

```
$ rg 'Dcutr with remote peer: PeerId\("\w+"\) is: Ok' --search-zip --count --stats
..
66857 matches
..
```


```
$ rg 'Dcutr with remote peer: PeerId\("\w+"\) is: Err' --search-zip --count --stats
..
2561083 matches
..
```

However, I haven't been able to reproduce this rate. Running a `--home-network` node on the WLAN at a tennis academy gives me no errors, only success (423 matches in my log file). Though I haven't run it as long as these nodes above.
