### ISSUE TITLE
The beta rewards secret key should be supplied to the auditor in testnet deployments

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#1744]
We can make the necessary extensions without the real secret key, then supply the real key when we are ready.

- [x] Provide an optional `--beta-encryption-key` argument on the `testnet-deploy` `deploy` command
- [x] Extend `sn-testnet-action` with a `beta-encryption-key` input
- [x] Extend the GHA `Launch Testnet` workflow to suppy the encryption key from a secret
- [ ] Supply the real secret key to the `Launch Testnet` workflow

**Comment by maqi** [comment]
It's actually shall be the key of payment_forward to be loaded into sn_auditor ?
According to the title, seems BOTH shall be supplied into the flow ?

note : the correspondent PK shall be updated in the code base to reflect the injection, and be used in the release build

**Comment by jacderida** [comment]
I think I have probably taken this as far as I can on my side, so I'm removing the assignment from myself.

Based on Qi's comment, we may perhaps need an additional step on providing the corresponding public key somewhere?
