### ISSUE TITLE
All earnings being sent back to foundation even with no Owner / Discord Username Set

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/autonomi#1771]
As per this forum post, users appear to report that all node earning are being sent back to foundation even if they haven't set an owner / opted in to the rewards program by inputting Discord User Name.

Node earnings should stay in local wallet if there is no Discord Username / owner set.

Unsure if this was via launch pad or just node manager.

https://forum.autonomi.community/t/thisisnotbetarewardsnet-mini-testnet-26-05-24/39824/77?u=jimcollinson

**Comment by maqi** [comment]
the formal reward phase will have no faucet, neither allow individual normal user to carry out any money transfer or upload.
this is to achieve `money consolidation`.
Hence, all earned payment has to be forwarded, even the owner is not set.
