### ISSUE TITLE
Determine best approach to reducing issues seen with cpu overload when starting many nodes

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#1810]
Nodes could safely during startup pause (ie, before they are in the network and behaving), so we could sample CPU/mem at startup and pause if too high.

Aim: A self regulating way to start many nodes at once? (ie avoid some magic "interval" that would be different depending on user's machine)

**Comment by Nic-dorman** [comment]
Determine best approach to reducing issues seen with cpu overload when starting many nodes

**Comment by RolandSherwin** [comment]
This PR https://github.com/maidsafe/safe_network/pull/2013 should solve this issue.
