### ISSUE TITLE
Users reporting Nano count disappearing from Launchpad when they stop and restart

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/autonomi#1849]
>I have a question about nanos -I left 50 nodes running last night and when I came in this morning there were 30 nanos earned. However when I stopped the nodes, (with the intention of rebooting just one or two while I work today) the Nanos Earned dropped to 0 and when I rebooted the node it did not show as started. I quit the launchpad and opened it up again and the single node now shows, but the Nanos earned is still at 0. 

and

>got same problem turned off my pc and my 30 nanos are gone

https://discord.com/channels/1209059621319221268/1247610908264628275/1248063487758831617

**Comment by Nic-dorman** [comment]
Check that we are correctly storing nanos in the launchpad.

**Comment by mickvandijke** [comment]
Hi @RolandSherwin ,

I'm looking into this issue currently and trying to get a grasp of how the node rewards and metrics work. 

So from my understanding, the launchpad queries the metrics API of every node, every few few ticks. The `Total Earned Nanos` value is then set to the `sn_node_total_forwarded_rewards` field in the metrics response.

I was wondering if the `sn_node_total_forwarded_rewards` field is persisted in between node reboots?

**Comment by RolandSherwin** [comment]
Hey @mickvandijke, yeah the value is stored to the disk and should be persisted between reboots.  This is where we update the value in the disk with the new one https://github.com/maidsafe/safe_network/blob/27bf1ac9f27349e61cb12456940294177f9886aa/sn_node/src/node.rs#L959-L960

The metrics server is also updated with this new value. (also set during startup). 
This is just for local tracking. The actual value will still be the one collected by the auditor.
