### ISSUE TITLE
No prompt to install Rosetta on non-intel Macs

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/autonomi#1850]
Users on Apple Silicon (M Series) Macs are reporting that the Node Launchpad is failing to operate, and log showing incompatibility with their CPU.

This is fixed by [installing Rosetta](https://support.apple.com/en-us/102527) but it appears they are not being prompted to do so by the OS on the first time install/run, as should be expected.

### Expected behaviour:
Mac users running apple silicon are to be prompted to install Rosetta when first running the launchpad.

**Comment by mickvandijke** [comment]
Could we not just add native release binaries for Apple Silicon (aarch64-apple-darwin) instead?

@joshuef @jacderida

**Comment by jacderida** [comment]
> Could we not just add native release binaries for Apple Silicon (aarch64-apple-darwin) instead?
> 
> @joshuef @jacderida

So we build the binaries on Github Actions infrastructure. I'm not sure if we would have access to that type of machine on there; however, if we did, it would be a good solution I think. We also use [cross](https://github.com/cross-rs/cross) for [cross compilation](https://github.com/maidsafe/safe_network/blob/b17a53615a574c3d8dc075669c24f6b8c0eb0ebc/Justfile#L120) of other `aarch64` binaries. Perhaps it may be possible to build for the other Apple architecture via that route?

If you could look into this, that would be great.

**Comment by mickvandijke** [comment]
> > Could we not just add native release binaries for Apple Silicon (aarch64-apple-darwin) instead?
> > @joshuef @jacderida
> 
> So we build the binaries on Github Actions infrastructure. I'm not sure if we would have access to that type of machine on there; however, if we did, it would be a good solution I think. We also use [cross](https://github.com/cross-rs/cross) for [cross compilation](https://github.com/maidsafe/safe_network/blob/b17a53615a574c3d8dc075669c24f6b8c0eb0ebc/Justfile#L120) of other `aarch64` binaries. Perhaps it may be possible to build for the other Apple architecture via that route?
> 
> If you could look into this, that would be great.

So it looks like that the `macos-latest` runner on GitHub already runs on Apple Silicon hardware as of Jan 30th 2024: https://github.com/actions/runner-images/issues/9254 . Therefore `cross` is probably not even needed.

I did a test run on my forked repo (https://github.com/mickvandijke/safe_network/actions/runs/10004518377) and tested the launchpad binaries on my M1 Mac, which seem to be running natively according to the activity monitor. Had no issues so far.

I did open a PR for it: https://github.com/maidsafe/safe_network/pull/1986
