### ISSUE TITLE
Fix bug: nodes cannot query spend parent nodes.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/autonomi#192]
Relies on the bug described in #207 to be solved.

The client can successfully query the network for the specific spend.
But when the close nodes of its child spend wants to ask the hodlers of the parent, they fail for some obscure reason.

**Comment by oetyng** [comment]
.

**Comment by maqi** [comment]
Issue resolved in the PR https://github.com/maidsafe/safe_network/pull/223,
with the previously disabled `multiple_sequential_transfers_succeed` test starts passing
