### ISSUE TITLE
refactor(cli): `wallet address` command should fail when no wallet is available instead of creating a new wallet

### ISSUE THREAD

**Issue by mickvandijke** [maidsafe/autonomi#1963]
The CLI command `wallet address` should simply print the address of the current wallet and nothing more. Currently, it will automatically generate a new wallet when no wallet is found. This behavior makes no sense to me when there is already a `wallet create` command. I propose that the `wallet address` command will be changed to ONLY print the address of the existing wallet or fail with an error: `No wallet found. Please create one using 'wallet create --help'`. And the existing wallet creation logic will be moved to the `wallet create` command.

https://github.com/maidsafe/safe_network/blob/main/sn_cli/src/bin/subcommands/wallet/hot_wallet.rs#L37

https://github.com/maidsafe/safe_network/blob/main/sn_cli/src/bin/subcommands/wallet/hot_wallet.rs#L138

**Comment by mazzi** [comment]
Makes sense to me.
@grumbach ?
@b-zee ?

**Comment by joshuef** [comment]
Seems reasonable.

I wonder if there are dependencies relying on this in tests... A CI run will flush that out though.

**Comment by b-zee** [comment]
Agreed. UNIX philosophy applies here, let tools do one thing and one thing right.

**Comment by mickvandijke** [comment]
Thank you for the quick responses. I will make a PR for this since all seem to be in agreement.
