### ISSUE TITLE
[Network] Filter out private addresses

### ISSUE THREAD

**Issue by mickvandijke** [maidsafe/autonomi#1994]
When looking at the logs here https://maidsafe.slack.com/archives/C07BC38RH6U/ we can see a lot of `MultiaddrNotSupported("/ip4/192.168.88.1` . This is a private address and the other peers should not have this as thier external address. We have a filter `multiaddr_is_global` that would prevent that, but something is off.

&ndash; As reported by @RolandSherwin

**Comment by RolandSherwin** [comment]
Fixed with https://github.com/maidsafe/safe_network/pull/2044
