### ISSUE TITLE
cli: make it clearer what the file address is after uploading a file in the console output

### ISSUE THREAD

**Issue by mickvandijke** [maidsafe/autonomi#2014]
When running the file upload command, on completion instead of outputting the file address next to the original filename: `<FILENAME> <FILE_ADDRESS>`, make it explicit that it is the file address: `File Address: <FILE_ADDRESS>`.

Example of what it outputs now (user has to guess that this is the file address):

```
safe_cli: "10KB-da03f3dac64ee2eb911f53fd6ce63efbf98e9c729d166a2b8194d316211ac2ff.bin" 76b689904c4b8121136d853afd5545d1cac269bdb97c21bfaa1c3f516467f875
```

Instead, do this:

```
safe_cli: "10KB-da03f3dac64ee2eb911f53fd6ce63efbf98e9c729d166a2b8194d316211ac2ff.bin", File Address: 76b689904c4b8121136d853afd5545d1cac269bdb97c21bfaa1c3f516467f875
```

Makes it easier for log parsers to find the file address :)

**Comment by happybeing** [comment]
FYI, if you are talking about the output to the terminal, the current arrangement was designed to match the parameters for `safe files download`.
