### ISSUE TITLE
Use traits to limit the exposure of certain `Network` APIs 

### ISSUE THREAD

**Issue by RolandSherwin** [maidsafe/autonomi#203]
Currently, the `Network` module contains functions such as `node_send_to_closest`, `client_send_to_closest`, etc. Thus, use traits to expose certain APIs when using the `Network` with `Node`/`Client`

[Reference](https://github.com/maidsafe/safe_network/pull/182#discussion_r1178128342)

**Comment by grumbach** [comment]
I'd be against using Traits when we can as they make code harder to reason with and less maintainable. I really don't think adding the complexity of traits here is a solution nor do I think this is would enhance the code in any way. Closing this for now, but please re-open this issue if you think I'm wrong.
