### ISSUE TITLE
Client-to-many-nodes-to-many-nodes messing fails.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/autonomi#207]
This bug is reproduced in PR #206.

The security and validation of DBCs in the network depend on the below described flow.
The referenced PR demonstrates the bug using an E2E test named `node_many_to_many_ping_pong_succeeds`.

***

A client sends a `ClientPing` to close group nodes of a given name.
Those nodes send a `NodePing` to close group nodes of the hash of the original name.
A node that receives a `NodePing`, will return `NodePong(Ok(()))` if it considers itself to be among the close group nodes of the given name.

The nodes receiving a `ClientPing`, will return a `NodePong(Ok(()))` if a majority of the nodes they queried, returned a `NodePong(Ok(()))`.

The test will succeed if the client receives a majority of `NodePong(Ok(()))`.

**Comment by oetyng** [comment]
Fixes [#192: nodes cannot query spend parent nodes](https://github.com/maidsafe/safe_network/issues/192).

**Comment by maqi** [comment]
Issue resolved.
The PingPong test got passed within the PR https://github.com/maidsafe/safe_network/pull/218.
