### ISSUE TITLE
Error: 0: trailing characters at line 1 column 7290

### ISSUE THREAD

**Issue by ukfhVp0zms** [maidsafe/autonomi#2089]
Receiving this error when running the provided `safenode-manager` and `node-launchpad` binaries, as well as when building the packages and running the binaries.

 ```
~/ RUST_BACKTRACE=full ./safe_network/target/release/safenode-manager add --count 1 --home-network
╔═══════════════════════════╗
║   Add Safenode Services   ║
╚═══════════════════════════╝
1 service(s) to be added
Error: 
   0: trailing characters at line 1 column 7290

Location:
   /home/impactviii/safe_network/sn_node_manager/src/cmd/node.rs:86

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮                               
   4: safenode_manager::main::{{closure}}::h80f8a32bf73d628b
      at <unknown source file>:<unknown line>
   5: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::hac0ce053a04e9cb8
      at <unknown source file>:<unknown line>
   6: tokio::runtime::context::runtime::enter_runtime::he209279b13c27e62
      at <unknown source file>:<unknown line>
   7: tokio::runtime::runtime::Runtime::block_on::h5da8d89d50619cb1
      at <unknown source file>:<unknown line>
   8: safenode_manager::main::h3955bebe0bbf33e8
      at <unknown source file>:<unknown line>
   9: std::sys_common::backtrace::__rust_begin_short_backtrace::hadc5745b1aa341ff
      at <unknown source file>:<unknown line>
  10: std::rt::lang_start::{{closure}}::h50ca1c8f1b7c2abb
      at <unknown source file>:<unknown line>
  11: std::rt::lang_start_internal::hc6d1267ee67d84b1
      at <unknown source file>:<unknown line>
  12: main<unknown>
      at <unknown source file>:<unknown line>
  13: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  14: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

```

**Comment by jacderida** [comment]
Thanks for the report.

What Linux distribution are you using?

**Comment by ukfhVp0zms** [comment]
> Thanks for the report.
> 
> What Linux distribution are you using?

Operating System: Arch Linux
Kernel Version: 6.10.8-arch1-1 (64-bit)

**Comment by jacderida** [comment]
Thanks. Also, are you running this command as the root user or as a normal account?

**Comment by ukfhVp0zms** [comment]
> Thanks. Also, are you running this command as the root user or as a normal account?

Normal account. It was running successfully until a few days ago.

**Comment by ukfhVp0zms** [comment]
Forgot to include the affected versions:

`sn-node-manager` 0.10.2
`node-launchpad` 0.3.13-node-launchpad-v0.3.13-1-g673bb7c0e (2024-09-07)

I'm not having any issues with `safenode cli`. It runs without any error messages.
`safenode cli` 0.110.1

**Comment by ukfhVp0zms** [comment]
Issue persists with

Operating System: Arch Linux
Kernel Version: 6.10.9-arch1-1 (64-bit)

for versions:
`sn-node-manager` 0.10.3
`node-launchpad` 0.3.14-token_supplies-v0.1.51 (2024-09-09)

**Comment by ukfhVp0zms** [comment]
Not sure which package it was, but after updating some system packages a few days ago, it started working again.

Thanks.
