### ISSUE TITLE
Restore use of file system chunk store.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/autonomi#211]
It has better performance (as shown [here](https://safenetforum.org/t/user-experience-for-the-clis/38101/334))   and less complexity than the kad storage.

The file store basically won't change anymore, and the msg handling is much simpler than the kad store version.

Also, it reduces the black box reliance on the kad store system.

**Comment by joshuef** [comment]
> It has better performance and less complexity than the kad storage.

Stats please!

Less complexity than handing it off to libp2p? 

>  Also, it reduces the black box reliance on the kad store system.

Seems in contrary to the above to me.

**Comment by joshuef** [comment]
Closing as we'll go for a RecordStore impl
