### ISSUE TITLE
Lower the client check during upload

### ISSUE THREAD

**Issue by maqi** [maidsafe/autonomi#243]
The current client requires ALL 8 OK resp to consider a chunk got succeed in uploading.
AND, a single incorrect resp will fail not only this chunk but the whole file uploading.

This is OK (or even required for a quick problem spotting) for our local test, but seems an overkill to the public testnet.

I personally experienced three times on uploading a 20MB file to public testnet, and the log shows all three failure is on just 1 out of 8 incorrect resp (that is received 7 OK resps but got 1 incorrect one after the time out).

It's suggest to only log the error and continue with the uploading when received majority OK resps, 
instead of a termination of upload flow.

**Comment by joshuef** [comment]
Sounds sensible 👍
