### ISSUE TITLE
Dead peers not detected

### ISSUE THREAD

**Issue by b-zee** [maidsafe/autonomi#300]
In an iteration of a public testnet, I observed a node that was offline and was repeatedly causing `OutgoingConnectionError` for all of the nodes in the network. This error occurred only about once every 30s.

We detect dead peers with a time sensitive cache, where we keep entries for 10s. This might be the root cause of the issue. We should think about the exact circumstances under which we evict dead peers. For example, raise the expire time and raise the threshold.

**Comment by joshuef** [comment]
That's a rebase issue, that should be sorted via [`62d8c5e` (#299)](https://github.com/maidsafe/safe_network/pull/299/commits/62d8c5e8d09462f44986dd7308dbb85e897ddb5f)

**Comment by b-zee** [comment]
Just making sure I understand. I rebased the TCP stuff, but I don't see I removed that functionality. As far as I can see, the behavior you mentioned wasn't in the original commit (https://github.com/maidsafe/safe_network/commit/0ad9d6497fe2262ad6f43a036169d5edab5c01cf)?

I'm pretty anxious with git/rebase sometimes, so I am trying to understand how this issue was caused by the rebase.

**Comment by joshuef** [comment]
I don't think you removed it, I think i did during the rebase work, misunderstanding what the final state should look like. 

I recall that point have a few branches and basically I think I clipped one by accident.
