### ISSUE TITLE
"libc.so.6: version `GLIBC_2.34' not found" on Ubuntu 20.04

### ISSUE THREAD

**Issue by happybeing** [maidsafe/autonomi#305]
Is it wise to use dynamic linking for `safenode`?

Running today's `safenode` (for the NAT test) I get the following error on an old version of Ubuntu (Ubuntu 20.04.1 LTS):

```bash
$ RUST_LOG=safenode ./safenode --log-dir=/tmp/safenode --root-dir=/tmp/safenodedata
./safenode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./safenode)
./safenode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./safenode)
./safenode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./safenode) 
```

I had something similar with the previous (JoshNet test) but cleared it up with `rustup update`. That hasn't helped this time and I see that the issue seems to be that older OS versions don't (can't?) support recent versions of these libs.

I recall that in the past a decision was made to switch to static linking to avoid this kind of issue so I am opening this to clarify whether that has been changed, and if so what the solution is going to be to this issue for laggard users?

For now I will not upgrade my cloud instance so I can test any suggested solutions.

A quick web search lead me to try `sudo apt install libc6` but this did not solve the issue (and reported `libc6 is already the newest version (2.31-0ubuntu9.9)`). I can though still run the joshnet `safenode` binary which seems odd.

I guess there would be a per-user-system workaround for this, but to ease running a node maybe we should avoid the issue if possible and revert to static linking?

**Comment by jacderida** [comment]
This is most likely because the Linux binary accidentally wasn't built using Musl. The binaries/releases are being provided manually just now. I'm working on a release process for the new repository, which will ensure the released binaries are always built with Musl.

**Comment by happybeing** [comment]
Looks at @b-zee 👀

🤣

**Comment by joshuef** [comment]
oohh, actually the linux bin was built using digital ocean, which _should_ be musl. Interesting if it's not!

**Comment by b-zee** [comment]
I tried building the binaries statically (musl) on my machine but got a compilation error. I later resolved the static build error on my machine with a `musl` dependency.

The (NatNet release) build is not static indeed :slightly_frowning_face::
```
$ ldd safenode
	linux-vdso.so.1 (0x00007ffc0abca000)
	libgcc_s.so.1 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libgcc_s.so.1 (0x00007fcb16c39000)
	libm.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libm.so.6 (0x00007fcb15920000)
	libc.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6 (0x00007fcb15600000)
	/nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/ld-linux-x86-64.so.2 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib64/ld-linux-x86-64.so.2 (0x00007fcb16c55000)
```

While my static build gives:
```
$ ldd target/x86_64-unknown-linux-musl/release/safenode
	statically linked
```
