### ISSUE TITLE
Payment and Storage

### ISSUE THREAD

**Issue by grumbach** [maidsafe/autonomi#615]
This comes after #613 #614 

Once the client knows the price for storing a chunk from asking the nodes in the close group of the data (`GetStoreCost`), it will pay them by uploading the payment DBCs with the proper reason field that was agreed on. That reason field would be the chunk's hash. 
Sending the Chunk along with the payment information.

**Comment by joshuef** [comment]
If have a `FeeOutput` on DBCs at the moment which contains the logic we need there. I'm not sure if we'd be scrapping that as that's not needed if we don't have the merkle setup?

**Comment by grumbach** [comment]
#721
