### ISSUE TITLE
Only store data upon replication if coming from relevant nodes

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#641]
We want to only store data if a majority of the close group of that data has the data.

The data should also be relevant only to this CLOSE_GROUP (i think we have this check already)

**Comment by joshuef** [comment]
If data insertion is a real concern we can increase this to require a majority over the data

**Comment by RolandSherwin** [comment]
Do we still need majority on replication? As per the discussion on slack, if we check that the payment has been made to `maj(closest_peers_to_data)`, and if we accept only the data close to us on replication, then we don't need a quorum on replication.
