### ISSUE TITLE
Automated Testnet Deployment

### ISSUE THREAD

**Issue by jacderida** [maidsafe/autonomi#643]
A list of work related to the automated deployment of testnets. Completing would draw a line under the deployment process for now.

- [x] Complete merge of the `ansible-run` branch on `sn-testnet-deploy`
- [x] Automate deployment of the faucet
- [x] Pull and reassemble logs on S3
- [x] Update the GHA workflows to use the new `sn-testnet-deploy` repository
- [x] Automatically upload a network contacts file
- [x] Reconfigure log forwarding setup to use Filebeat and Logstash
- [x] Basic automated smoke testing to determine a network is good to be made public to the community (check connections, upload small files etc.)
----
Some points from @joshuef

- [x] Use image for build tasks (it's much faster)
- [x] Build faucet w/ build tasks (client/faucet/node should all come from the same commit)
- [x] Automate upload of initial test data (this exists on my branch; you have this with smoke)
- [x] Post a link to slack with contact file + logs location for testnet
----
Non essential work:
* Add the RPC client binary to the release process (not necessary, but would be nice for completion and consistency)
* Add the faucet binary to the release process (without a release we would need to build it during the deploy process)
* Incorporate `aarch64` Raspberry Pi into testnet participation for install and general testing
* Incorporate `armv7` Raspberry Pi into testnet participation for install and general testing

Notes:
The network contacts file was not deemed strictly necessary and was considered covered by the fact that the testnet-deploy tool outputs a list of peers in the inventory report.

**Comment by joshuef** [comment]
Done and done 💪 🙇
