### ISSUE TITLE
Files upload output is not cut n paste friendly

### ISSUE THREAD

**Issue by willief** [maidsafe/autonomi#890]
https://safenetforum.org/t/heapnet2-testnet-12-10-23/38749/460?u=southside

Make sharing upload results as easy as possible and encourage others to test downloads.

Change 
```
**************************************
*          Uploaded Files            *
**************************************
Uploaded History of Stuff 1980-2023.pdf to 1d1e081fbf7b37f2156f3f428ead2ecb31f7b91b0a4239564eb426cffca65e0f
```
to 
```

**************************************
*          Uploaded Files            *
**************************************
"History of Stuff 1980-2023.pdf" 1d1e081fbf7b37f2156f3f428ead2ecb31f7b91b0a4239564eb426cffca65e0f

```
This output then can be pasted directly into `safe files download` for immediate testing or can be quickly posted to an Uploads wiki page on the forum.

**Comment by joshuef** [comment]
Sortred via 25d24fd367a6a68e553be5ee8eb9b0537792fa04
