### ISSUE TITLE
`req_response_timeout` does not work in `Client::new`

### ISSUE THREAD

**Issue by loziniak** [maidsafe/autonomi#899]
I think connection timeout argument is not working as expected in client.

My code (based on `sn_node/examples/registers.rs`):
```rust

let peers = sn_peers_acquisition::parse_peers_args(
  sn_peers_acquisition::PeersArgs { peers: vec![], network_contacts_url: None }
).await.map_err(|e| e.to_string())?; 
println!("peers: {:?}", &peers);

let signer = SecretKey::random();
println!("Starting SAFE client...");
let client = Client::new(signer, Some(peers), Some(Duration::from_secs(10))).await.map_err(|e| e.to_string())?;
```

and it hangs on connection forever:

```
[...] "/ip4/142.93.37.47/tcp/35095/p2p/12D3KooWAM69wQsCG6ecYRk4idcGPfmDugW2ri5DxwQkiZobdNBW", "/ip4/161.35.166.121/tcp/44247/p2p/12D3KooW9uoQfCTDrofzpT6t465AgSA1pqtLzxpHwXoRoGfpXchE", "/ip4/167.99.206.43/tcp/40251/p2p/12D3KooWAYnquy8Mwf1ibs6Z1kEiY4WvNj2mMbERWiWZW82WLNEJ", "/ip4/143.110.166.254/tcp/41089/p2p/12D3KooWBZLdZRAmjwSnwvtZPJ1gT6Je9QxfzgccKFjreZa4Krf2", "/ip4/209.97.180.3/tcp/34385/p2p/12D3KooW9sjaU6Sc2fkdqWTgty3zu8B3NcJL6ubEbhZptzx8ef2p", "/ip4/188.166.149.100/tcp/45039/p2p/12D3KooWB4LrRjPRWrYq7sN3cHCVfLa6pWXYNcrVKjd1eTtUHSaT"]
Starting SAFE client...
⠄ Connecting to The SAFE Network...
```

**Comment by RolandSherwin** [comment]
The `request_timeout` in the Client args refers to the timeout of the internal `RequestResponse` protocol. I.e, it should affect the timeout when querying nodes for storecost etc. 
Currently there is no way for the client to timeout when it cannot connect to the network. But I think it might be useuful to add an arg for `connection_timeout`.

Also we can remove the `request_timeout` from the Client arg as its impact is much lower than say, `kad_timeout` c.c @joshuef

**Comment by joshuef** [comment]
@RolandSherwin was this addressed? can we close?

**Comment by RolandSherwin** [comment]
> @RolandSherwin was this addressed? can we close?

Yes. We now have a `connection_timeout` argument.
