### ISSUE TITLE
Strange error handling in cli wallet commands

### ISSUE THREAD

**Issue by loziniak** [maidsafe/autonomi#913]
Hello, I noticed something strange in CLI code:

https://github.com/maidsafe/safe_network/blob/46e7c539099c35876884abacf457b878f9eacb04/sn_cli/src/subcommands/wallet.rs#L347

Errors in `send()` and `receive()` functions are silently discarded. Only explanation of that is to exit without error, and it can work with `send()`, but `receive()` is used also in `get_faucet()`, where after "successful" receive we get a "Successfully got tokens from faucet." message, which is not true for `return Ok(());` lines – if the transfer was not parsed, verified or redeemed.

**Comment by joshuef** [comment]
Thanks for this @loziniak.

Do you fancy trying to tackle this? Happy to provide guidance if any is needed!

**Comment by loziniak** [comment]
Sure! #949
